<?php

namespace ContainerYuZPlTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_3N_84aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.3N._84a' shared service.
     *
     * @return \App\Controller\ZgloszeniaRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\BaseController::mojezgloszenia()": the $repository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ZgloszeniaRepository". Did you forget to add a use statement?');
    }
}
