<?php

namespace ContainerYuZPlTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JaZGl7FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jaZGl7F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jaZGl7F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repository' => ['privates', '.errored.3N._84a', NULL, 'Cannot determine controller argument for "App\\Controller\\BaseController::mojezgloszenia()": the $repository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ZgloszeniaRepository". Did you forget to add a use statement?'],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'entityManager' => '?',
            'repository' => '?',
            'security' => '?',
        ]);
    }
}
