<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRXq9q0a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRXq9q0a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRXq9q0a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRXq9q0a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRXq9q0a\App_KernelDevDebugContainer([
    'container.build_hash' => 'RXq9q0a',
    'container.build_id' => '071128e3',
    'container.build_time' => 1686154051,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRXq9q0a');
